### PR TITLE
A hacky fix for #574

### PR DESCRIPTION
**Pull request by mottykohn**
It works but obviously could be better. Just sharing for the interim.

### CODE REVIEW

**Comment by mottykohn** [comment]
Did not test if this breaks pre ui-router 1.0.

**Comment by rohitnarula7176** [comment]
@mottykohn Thank you for your contribution. $transitions is not available as a dependency for ui-router versions <1.0. We will need a solution that works for both pre and post ui-router release 1.0.

**Comment by mottykohn** [comment]
@rohitnarula7176 Sorry for late response. I believe I fixed it now.

**Comment by wy193777** [comment]
What's the status for this now? I've spent 2 days on this issue and finally find the problem. Can someone merge it?

**Comment by wy193777** [comment]
Any update?

**Comment by navyasric** [comment]
@wy193777 @rohitnarula7176 is looking into the PR

**Pull request merged**
