### PR TITLE
Added renewStates to window

### LINKED ISSUE #460: Importing adal.js as a module breaks token refresh
There is some module loading code in adal.js, so I tried bundling it with webpack and "require"ing it.  everything seemed to work fine till I went to refresh and the code at https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L796 tried to see if the IFrame window.parent.AuthenticationContext was defined.  When importing as a module that property isn't defined.  At that point the rest of the code thinks that the state didn't match.

### PR DESCRIPTION
**Pull request by rohitnarula7176**
Fixes #460 #543

### CODE REVIEW

**Comment by lovemaths** [comment]
:shipit:

**Comment by nybroe** [comment]
Have these changes been removed again?
I can see that in the latest version you are still adding renewStates to the current context (this) and not the window as the changes in this PR states.

**Comment by rohitnarula7176** [comment]
@nybroe The name of the PR is misleading. We only changed the logic once where we moved properties renewStates, callBackMappedToRenewStates and callBacksMappedToRenewStates from window to the private Adal instance as they were causing problems when consumed in webpack in the case when the module name was defined as AuthenticationContext (the same name Adal exports as global on the window)

**Comment by nybroe** [comment]
@rohitnarula7176 Thank you for the quick response. Even though all the properties are moved to the adal instance, I can still see that _renewStates and others are empty or undefined when read through the iframe.
Please take a look at my newly created issue. :)
[https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/710](url)

**Pull request merged**
