### PR TITLE
fix unuseful start of react or other js SPA application

### PR DESCRIPTION
**Pull request by salvoravida**
Fix unuseful start of react or other js SPA application on callback Url just before redirect.

index.js of an SPA application like ReactJs may disable all JS script on callback if it will redirected just after. 

this will provide better performance on redirection.

i need this on react-adal : https://github.com/salvoravida/react-adal

Salvo.

### CODE REVIEW

**Comment by salvoravida** [comment]
please coulf you merge this small but very importanst change?

thank you.

**Comment by salvoravida** [comment]
why you ignore this small but very important fix for using in react apps?

**Comment by salvoravida** [comment]
please merge this mod, react-adal cannot work fine without it.
so i cannot update to new version of adal.js

are you there? do you read it?

**Comment by rohitnarula7176** [comment]
@salvoravida Thank you for your pull request. I have merged your changes.

**Comment by salvoravida** [comment]
great!

**Pull request merged**
