### PR TITLE
Ability to bypass Authorization requests

### PR DESCRIPTION
**Pull request by bholdt**
Sometimes you don't want the authorization token added.

The way you could do that from client side now, would be

$http({
   method: 'GET',
   url: '/some/url',
   skipAuthorization: true
})
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/163%23issuecomment-139449050%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/163%23issuecomment-144880187%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/163%23issuecomment-139449050%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40bholdt__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-09-11T04%3A18%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9287708%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msftclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40bholdt%20Thanks%20for%20bringing%20this%20up.%20We%20need%20more%20consideration%20for%20this.%20%22%2C%20%22created_at%22%3A%20%222015-10-01T23%3A54%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/weijjia%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/163#issuecomment-139449050'>General Comment</a></b>
- <a href='https://github.com/msftclas'></a> Hi __@bholdt__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSBOT;
- <a href='https://github.com/weijjia'></a> @bholdt Thanks for bringing this up. We need more consideration for this.

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/163?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/163?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/163'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/163'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by weijjia** [comment]
@bholdt Thanks for bringing this up. We need more consideration for this.

**Comment by tylerjwatson** [comment]
+1 for this feature. 

I am doing an in-house application where users may authenticate via Azure AD or via standalone accounts in a hybrid-authentication scenario.  It is imperative that this hybrid scheme be maintained because not all users of the system will have directory accounts.

Currently, the http interceptor is destructive and will reject every `$http` request matching an endpoint if it is installed in the interceptor pipeline and ADAL is not actually being used as the authentication scheme.  It would be a very useful feature to disable ADAL on requests via a flag at runtime.

**Comment by tushargupta51** [comment]
@bholdt @tylerjwatson We have added an extensibility point: `adal.config.anonymousEndpoints`. You can specify the urls/paths which you want interceptor to ignore. If you specify "app/views", it will ignore "app/views", "app/views/home.html", "app/views/about.html".

I am closing this PR, please let us know if you have any questions.

**Pull request closed without merging**
