### PR TITLE
Proposed fix for issue #151. New config setting for iframe redirect uri.

### PR DESCRIPTION
**Pull request by Neil665**
This can be used to prevent the situation where the entire application is
re-created inside the iframe.

See further details at:
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/259#issuecomment-216691463

### CODE REVIEW

**Comment by tushargupta51** [comment]
@Neil665 Thanks for your contribution :) We would like to merge your changes to our dev branch for next release. It seems you need a rebase.
Also, can you pass the "false" flag in login method where it calls `getNavigateUrl`? I know, its not needed but its good to pass it explicitly.

**Comment by tushargupta51** [comment]
@Neil665 On second look at this PR, this solution will require users to register `frameRedirectUri` as one of the reply address in AAD portal for this to work. In that case, they can just assign the special html  to the `redirectUri` property. In case of login, adal saves the start page and redirect the user back to it once login process is completed. So, the user experience will not change even when the redirect_uri is referring to the special html file.

**Comment by Neil665** [comment]
@tushargupta51 We didn't need to make any change in the AAD portal. Our adal-frame.html file is located under the same path as our main application so it is already covered by the return url that was registered with AAD for the main application.

**Comment by Neil665** [comment]
@tushargupta51 I have made the change that you requested (adding the "false" flag to the method call).
I have not done a rebase as I'm not clear on your exact process, e.g. whether commits should be squashed. Is this documented somewhere?
(Also there was another change we had to make to the library which I have submitted as https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/316).

**Comment by tushargupta51** [comment]
@Neil665 Some internal partners who are using adal js and authenticating against ADFS reported that they needed to add frameRedirect uri as a valid redirect uri for this to work. In any case, why not just assign the special html path to `redirect_uri`?

**Comment by tushargupta51** [comment]
@Neil665  Thanks for you contribution. However, I think `redirectUri` can be used to specify the special frame redirect html and that won't require users to register 2 redirect_uri, both for AAD and ADFS. I have documented the solution here: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token. Please let me know if that doesn't work.

**Comment by ryanflowers** [comment]
Hello @tushargupta51 I am currently use adal.js "adal-angular": "1.0.17". I am not using the popup option but instead using the full auth redirect on login. I have the same issue listed here in that my app is loading in the iframe. So I created an auth.html which I serve at /auth.html. I overwrite the redirectUri in config post login to be "auth.html" as you described [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token). 

[Issue]
Lets say mid session I get a "login_required" on acquire token due to logout execution within another tab. I handle this by calling login(). The overwritten redirectUri is then used by adal.js on line 1532 which then redirects the user to the /auth.html instead of my app post login.

str.push('redirect_uri=' + encodeURIComponent(obj.redirectUri));

It feels like being explicit on two redirect uri's; one for top and one for iframe is much more straight forward and will lead to less bugs in adding the flexibility needed.

Any input here on direction would be really helpful. Thank you Tushar! BTW I know there is a new MSAL version which I would love to use but I have legacy blockers ATM.

**Pull request closed without merging**
