### PR TITLE
feat(storage): ability to pass a custom storage

### PR DESCRIPTION
**Pull request by 4F2E4A2E**
Some apps in the enterprise have the requirement to encrypt all it's client data on the storage.
This is a request for adal-angular to support a custom [localStorage](https://github.com/softvar/secure-ls) or a custom sessionStorage.

Closes https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/776

### CODE REVIEW

**Comment by 4F2E4A2E** [comment]
@weijjia @nehaagrawal Hey guys, any feedback on this PR would be much apreciated. travis-ci is failing, but not because of this PR directly, but broken dependencies in constellation with certain node versions. 

The ci must be broken in master as well, since another PR https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/777 with no changes in the functionality is also failing. 

Maybe the travis-ci &/ dependency problem should be adressed in another issue, are you guys on it?

**Comment by Arikael** [comment]
see #799 
I hope we can resolve this issue fast, because PRs are piling up

**Comment by 4F2E4A2E** [comment]
Can we get any updates on this one?

**Comment by 4F2E4A2E** [comment]
Why has it been closed without even a short notice?

**Pull request closed without merging**
