### PR TITLE
utf-8 character fix

### PR DESCRIPTION
**Pull request by manospasj**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/74%23issuecomment-70691517%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/74%23issuecomment-70728691%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/74%23issuecomment-70730192%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/74%23issuecomment-70691517%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thank%20you%20for%20the%20changes.%20Can%20you%20visit%20https%3A//cla.msopentech.com/%20and%20sign%20the%20Contributor%20License%20Agreement%3F%22%2C%20%22created_at%22%3A%20%222015-01-20T17%3A08%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/466805%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/omercs%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%20of%20course%21%22%2C%20%22created_at%22%3A%20%222015-01-20T20%3A40%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5380042%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/manospasj%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-01-20T20%3A49%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5380042%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/manospasj%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/74#issuecomment-70691517'>General Comment</a></b>
- <a href='https://github.com/omercs'></a> Thank you for the changes. Can you visit https://cla.msopentech.com/ and sign the Contributor License Agreement?
- <a href='https://github.com/manospasj'></a> Yes of course!

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/74?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/74?approve=1'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/74'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/74'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by omercs** [comment]
Thank you for the changes. Can you visit https://cla.msopentech.com/ and sign the Contributor License Agreement?

**Comment by manospasj** [comment]
Yes of course!

**Comment by manospasj** [comment]
:+1:

**Pull request merged**
