### PR TITLE
readme: add setup step addressing necessary config for HTML5Mode

### PR DESCRIPTION
**Pull request by rdmchenry**
When HTML5Mode is configured, if $locationProvider hashPrefix is
not set, the login sequence goes into an infinite loop. This
happens because, in HTML5Mode, the $locationProvider rewrites all
URLs to remove the hash+hashPrefix and AAD uses the hash to pass
the token via the redirect to the authenticating app. The logic
in ADAL.js fails to find the token as the hash is removed when
no hashPrefix is defined causing the token parse to fail and
ultimately the client-side authentication.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/152%23issuecomment-122091900%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/152%23issuecomment-122096541%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/152%23issuecomment-122116982%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/152%23issuecomment-122091900%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Hi%20__%40rdmchenry__%2C%20I%27m%20your%20friendly%20neighborhood%20Microsoft%20Open%20Technologies%2C%20Inc.%20Pull%20Request%20Bot%20%28You%20can%20call%20me%20MSOTBOT%29.%20Thanks%20for%20your%20contribution%21%5Cr%5Cn%20%20%20%20%3Cspan%3E%5Cr%5Cn%20%20%20%20%20%20%20%20This%20seems%20like%20a%20small%20%28but%20important%29%20contribution%2C%20so%20no%20Contribution%20License%20Agreement%20is%20required%20at%20this%20point.%20Real%20humans%20will%20now%20evaluate%20your%20PR.%5Cr%5Cn%20%20%20%20%3C/span%3E%5Cr%5Cn%5Cr%5CnTTYL%2C%20MSOTBOT%3B%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-07-16T20%3A57%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22__%40rdmchenry__%2C%20Thanks%20for%20signing%20the%20contribution%20license%20agreement%20so%20quickly%21%20Actual%20humans%20will%20now%20validate%20the%20agreement%20and%20then%20evaluate%20the%20PR.%5Cr%5Cn%3Cbr%20/%3EThanks%2C%20MSOTBOT%3B%22%2C%20%22created_at%22%3A%20%222015-07-16T21%3A08%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9519461%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/msotclas%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-07-16T22%3A03%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5150561%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rdmchenry%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/rdmchenry%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5150561%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/rdmchenry'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/152#issuecomment-122091900'>General Comment</a></b>
- <a href='https://github.com/msotclas'></a> Hi __@rdmchenry__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
<span>
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
</span>
TTYL, MSOTBOT;
- <a href='https://github.com/msotclas'></a> __@rdmchenry__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/152?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/152?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/152?approve=0'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/152'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/152'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by msotclas** [comment]
Hi __@rdmchenry__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@rdmchenry__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by rdmchenry** [comment]
:shipit:

**Pull request merged**
