### PR TITLE
Dev fix inceptor call

### PR DESCRIPTION
**Pull request by weijjia**
ignore interceptor call if the usl is not app backend or not listed in the endpoint structure
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/168%23issuecomment-146007336%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/168%23issuecomment-146736542%22%2C%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/168%23issuecomment-147798214%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/AzureAD/azure-activedirectory-library-for-js/pull/168%23issuecomment-146007336%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Is%20it%20possible%20to%20add%20a%20test%20case%20for%20this%20as%20well%3F%22%2C%20%22created_at%22%3A%20%222015-10-06T21%3A28%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RandalliLama%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-09T02%3A01%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1166233%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/weijjia%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-13T18%3A06%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/RandalliLama%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/RandalliLama%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4307330%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/RandalliLama'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/168#issuecomment-146007336'>General Comment</a></b>
- <a href='https://github.com/RandalliLama'></a> Is it possible to add a test case for this as well?

<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/168?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/168?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/AzureAD/azure-activedirectory-library-for-js/pull/168?approve=0'></a>&nbsp;<a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/168'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by brandwe** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/168'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by RandalliLama** [comment]
Is it possible to add a test case for this as well?

**Comment by weijjia** [comment]
Sure, added a few test cases.

**Comment by RandalliLama** [comment]
:shipit:

**Pull request merged**
